### PR TITLE
enhance UX :sparkles:

### PR DESCRIPTION
**Pull request by dtaylor-us**

### CODE REVIEW

**Comment by dtaylor-us** [comment]
I have updated this pull request with your latest commits 👌

**Comment by outcastgeek** [comment]
> I have updated this pull request with your latest commits 👌

**Comment by outcastgeek** [comment]
> I have updated this pull request with your latest commits 👌

Thank you!

**Comment by outcastgeek** [comment]
> I have updated this pull request with your latest commits 👌

Thank you!

**Pull request merged**
